@startuml
class Line {
    -coor1: Vector2
    -coor2: Vector2
    +classes: string[]
    +visible: boolean
    +transform: Transformation
    +setTransform(transform: Transformation): Line
    +getTransformedX1(): number
    +getTransformedY1(): number
    +getTransformedX2(): number
    +getTransformedY2(): number
    +setX1(x1: number): Line
    +getX1(): number
    +setY1(y1: number): Line
    +getY1(): number
    +setX2(x2: number): Line
    +getX2(): number
    +setY2(y2: number): Line
    +getY2(): number
    +setCoor1(coor: Vector2): Line
    +getCoor1(): Vector2
    +setCoor2(coor: Vector2): Line
    +getCoor2(): Vector2
    +setVisible(visible: boolean): Line
    +isVisible(): boolean
    +getClasses(): string[]
    +translate(shift: Vector2): Line
}
class Circle {
    -coor: Vector2
    +radius: number
    +scale: number
    +visible: boolean
    +transform: Transformation
    +setTransform(transform: Transformation): Circle
    +getTransformedX(): number
    +getX(): number
    +setX(x: number): Circle
    +getTransformedY(): number
    +getY(): number
    +setY(y: number): Circle
    +setCoor(coor: Vector2): Circle
    +getCoor(): Vector2
    +getTransformedCoor(): Vector2
    +getScaledRadius(): number
    +setScale(scale: number): Circle
    +setVisible(visible: boolean): Circle
    +isVisible(): boolean
    +getClasses(): string[]
    +translate(shift: Vector2): Circle
}
class Rectangle {
    -coor: Vector2
    +width: number
    +height: number
    +classes: string[]
    +visible: boolean
    +transform: Transformation
    +setTransform(transform: Transformation): Rectangle
    +getTransformedX(): number
    +getX(): number
    +setX(x: number): Rectangle
    +getTransformedY(): number
    +getY(): number
    +setY(y: number): Rectangle
    +setCoor(coor: Vector2): Rectangle
    +getCoor(): Vector2
    +setVisible(visible: boolean): Rectangle
    +isVisible(): boolean
    +getWidth(): number
    +getHeight(): number
    +getClasses(): string[]
    +translate(shift: Vector2): Rectangle
}
class Text {
    +text: string
    -coor: Vector2
    +classes: string[]
    +visible: boolean
    +transform: Transformation
    +setTransform(transform: Transformation): Text
    +getTransformedX(): number
    +getX(): number
    +setX(x: number): Text
    +getTransformedY(): number
    +getY(): number
    +setY(y: number): Text
    +setCoor(coor: Vector2): Text
    +getCoor(): Vector2
    +setVisible(visible: boolean): Text
    +isVisible(): boolean
    +getText(): string
    +getClasses(): string[]
    +width(styles: Styles): number
    +translate(shift: Vector2): Text
}
class Vector2 {
    +x: number
    +y: number
    +add(vector: Vector2): Vector2
    +subtract(vector: Vector2): Vector2
    +multiply(k: number): Vector2
    +size(): number
    +copy(): Vector2
    +{static} zero: Vector2
    +{static} sum(vector1: Vector2, vector2: Vector2): Vector2
    +{static} subtraction(vector1: Vector2, vector2: Vector2): Vector2
    +{static} distance(vector1: Vector2, vector2: Vector2): number
}
@enduml
